const RESERVATION_RULES = {
    OPENING_TIME: "17:00",
    CLOSING_TIME: "23:00",
    SLOT_INTERVAL_MINUTES: 30,
    MAX_GUESTS_PER_SLOT: 40,
    MAX_PARTY_SIZE: 12,
};

export default RESERVATION_RULES;